name: rtc_aigc_plugin
description: A Flutter plugin for RTC AIGC API integration.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.1.0
  crypto: ^3.0.3 # for crypto
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: RtcAigcPlugin
        fileName: rtc_aigc_plugin.dart

  assets:
    - sdk/volengine_Web_4.66.1.js
