name: volc_engine_rtc_web
description: A Flutter plugin for Volc Engine RTC with AIGC, enabling interactive real-time voice conversations with AI assistants in Flutter web apps.
version: 0.1.0
repository: https://github.com/chenyeju295/volc_engine_rtc_web
homepage: https://github.com/chenyeju295/volc_engine_rtc_web
 
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.3.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: RtcAigcPlugin
        fileName: volc_engine_rtc_web.dart

